App\Entity\Twitt:
    properties:
        body:
            - NotBlank: ~
            - Length:
                min: 6
                max: 9
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name'
