index:
    path: /
    controller: App\Controller\MainController::index

getInfo:
    path: /getInfo/{id}
    controller: App\Controller\MainController::getInfo

gettwitter:
    path: /twitter
    controller: App\Controller\TwitterController:index
    methods:    GET

postTwitter:
    path: /twitter
    controller: App\Controller\TwitterController:insert
    methods:    POST
